"""add Keycloak identity fields

Revision ID: 7f4ffd64a291
Revises: a21491100d85
Create Date: 2026-09-09 05:18:39.562417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4ffd64a291'
down_revision: Union[str, Sequence[str], None] = 'a21491100d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_issuer', sa.String(length=512), nullable=False))
    op.add_column('users', sa.Column('keycloak_subject', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_users_keycloak_identity', 'users', ['keycloak_issuer', 'keycloak_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_keycloak_identity', 'users', type_='unique')
    op.drop_column('users', 'keycloak_subject')
    op.drop_column('users', 'keycloak_issuer')
    # ### end Alembic commands ###
